---
- name: Backup and Restore Network Device Configurations
  hosts: network_devices
  gather_facts: no
  vars:
    backup_path: "/backup/configs/{{ inventory_hostname }}"
    restore_path: "/tmp/configs/{{ inventory_hostname }}"
  tasks:
    - name: Backup configuration
      ios_command:
        commands:
          - show running-config
      register: config
    - name: Create backup directory
      file:
        path: "{{ backup_path }}"
        state: directory
    - name: Save configuration to backup directory
      copy:
        content: "{{ config.stdout[0] }}"
        dest: "{{ backup_path }}/config"
    - name: Restore configuration
      ios_config:
        src: "{{ restore_path }}/config"
      when: restore is defined
    - name: Create restore directory
      file:
        path: "{{ restore_path }}"
        state: directory
      when: restore is defined
    - name: Copy backup configuration to restore directory
      copy:
        src: "{{ backup_path }}/config"
        dest: "{{ restore_path }}/config"
      when: restore is defined
